name: Validate Pull Request Source Branch and Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, tokenizer, xml

      - name: Verify Files
        run: |
          echo "Verificando estrutura inicial do projeto:"
          ls -la

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --verbose
          echo "Conteúdo do diretório raiz após composer install:"
          ls -la
          echo "Conteúdo do diretório 'vendor':"
          ls -la vendor || echo "Diretório 'vendor' não encontrado. Dependências não foram instaladas corretamente."

      - name: Check PR source branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "ERRO: Apenas pull requests da branch 'dev' são permitidos."
            exit 1
          fi

  
