name: Validate Pull Request Source Branch and Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Cache Composer Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist
          ls -la vendor  # Verifica se o diretório vendor foi gerado

      - name: Check PR source branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "ERRO: Apenas pull requests da branch 'dev' são permitidos."
            exit 1
          fi

  test:
    runs-on: ubuntu-latest
    needs: check-pr-branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl
          coverage: xdebug

      - name: Set up .env file for testing
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --env=testing --force

      - name: Verify Vendor Directory
        run: ls -la vendor

      - name: Run Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml --testdox
