name: Validate Pull Request Source Branch and Run Tests

on:
  pull_request:
    branches:
      - main  # Dispara o workflow quando há um pull request para a branch 'main'

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest  # Ambiente de execução do Ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Faz o checkout do código para a máquina de CI

      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Define a versão do PHP para 8.2

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist  # Instala as dependências do Composer
          
      - name: Check PR source branch
        run: |
          if [[ "${{ github.head_ref }}" != "dev" ]]; then
            echo "ERRO: Apenas pull requests da branch 'dev' são permitidos."
            exit 1
          fi
